---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/8 17:10
---

--- @class MainWindow : BaseWindow
local MainWindow = Class.CreateClass("MainWindow", "BaseWindow")

function MainWindow:New()
    self.windowType = UIManager.WindowType.Main
    self.prefabPath = "Window/MainWindow"
end

function MainWindow:OnInit()
    self.__super.OnInit(self)
end

function MainWindow:InitEvent()
    self.btnOpen = self.gameObject.transform:Find("btnOpen"):GetComponent(typeof(Button))
    self.btnClose = self.gameObject.transform:Find("btnClose"):GetComponent(typeof(Button))

    self:AddListener(self.btnOpen.onClick, self.ClickBtnOpen)
    self:AddListener(self.btnClose.onClick, self.ClickBtnClose)
end

function MainWindow:OnShowing()
    self:InitEvent()
    self:InitInfo()

    self.__super.OnShowing(self)
end

function MainWindow:InitInfo()
    local rawImage = self.gameObject.transform:Find("bgImg"):GetComponent(typeof(RawImage))
    self:SetTexture(rawImage, "Texture/迪迦的肯定", true)
end

function MainWindow:ClickBtnOpen()
    UIManager.OpenUI("TestWindow1")
end

function MainWindow:ClickBtnClose()
    --UIManager.CloseUI("MainWindow")
    self.uiElements.title.text = 111
    --self.uiElements.testElement.name.text = "I did it!!"
    self.uiElements.txt.text = "BCD"
end

function MainWindow:OnClose()
    self.__super.OnClose(self)
end

return MainWindow