---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/9 15:36
---

--- @class TestWindow1 : BaseWindow
local TestWindow1 = Class.CreateClass("TestWindow1", "BaseWindow")

function TestWindow1:New()
    self.windowType = UIManager.WindowType.Window
    self.prefabPath = "Window/TestWindow"
end

function TestWindow1:OnInit()
    self.__super.OnInit(self)
end

function TestWindow1:InitEvent()
    self.btnOpen = self.gameObject.transform:Find("btnOpen"):GetComponent(typeof(Button))
    self.btnClose = self.gameObject.transform:Find("btnClose"):GetComponent(typeof(Button))

    self:AddListener(self.btnOpen.onClick, self.ClickBtnOpen)
    self:AddListener(self.btnClose.onClick, self.ClickBtnClose)
end

function TestWindow1:OnShowing()
    self:InitEvent()
    self.__super.OnShowing(self)
end

function TestWindow1:ClickBtnOpen()
    UIManager.OpenUI("TestWindow2")
end

function TestWindow1:ClickBtnClose()
    UIManager.CloseUI("TestWindow1")
end

function TestWindow1:OnHide()
    self.__super.OnHide(self)
end

function TestWindow1:OnClose()
    self.__super.OnClose(self)
end

return TestWindow1