---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/10 17:10
---

--- @class TestWindow3 : BaseWindow
local TestWindow3 = Class.CreateClass("TestWindow3", "BaseWindow")

function TestWindow3:New()
    self.windowType = UIManager.WindowType.Pop
    self.prefabPath = "Window/TestWindow"
end

function TestWindow3:OnInit()
    self:Super().OnInit(self)
end

function TestWindow3:OnShowing()
    self:InitEvent()
    self:InitData()
    self:InitInfo()

    self:Super().OnShowing(self)
end

function TestWindow3:InitEvent()
    self.btnOpen = self.gameObject.transform:Find("btnOpen"):GetComponent(typeof(Button))
    self.btnClose = self.gameObject.transform:Find("btnClose"):GetComponent(typeof(Button))

    self:AddListener(self.btnOpen.onClick, self.ClickBtnOpen)
    self:AddListener(self.btnClose.onClick, self.ClickBtnClose)

    self:AddListener(self.uiElements.btnSendEvent.onClick, function ()
        EventManager.DispatchEvent(EventID.TestEventId1, "Hello World!!")
    end)

    --self:AddEvent(EventID.TestEventId1, function (args)
    --    self.uiElements.title.text = args
    --end)

    self:AddEvent(EventID.TestEventId1, function(args, a)
        self.uiElements.title.text = a
    end)
end

function TestWindow3:InitData()

end

function TestWindow3:InitInfo()

end

function TestWindow3:ClickBtnOpen()
    UIManager.OpenUI("TestWindow4")
end

function TestWindow3:ClickBtnClose()
    UIManager.CloseUI("TestWindow3")
end

function TestWindow3:OnHide()
    self:Super().OnHide(self)
end

function TestWindow3:OnClose()
    --self:RemoveEvent(EventID.TestEventId1, function(args, a)
    --    self.uiElements.title.text = a
    --end)
    self:Super().OnClose(self)
end

return TestWindow3