--- 资源管理器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/9 15:54
---

--- @class ResourceManager
local ResourceManager = {}
_G.ResourceManager = ResourceManager

--- LoadPrefab 加载预制体
--- @param parent Transform 父物体
--- @param prefabPath string 预制体路径  不传默认为：UICanvas
--- @param callback function 加载完成回调
function ResourceManager.LoadPrefab(parent, prefabPath, callback)
    CS_ResourceManager.LoadPrefab(parent or UIRoot, prefabPath, callback)
end

--- LoadPrefab 同步加载预制体
--- @param parent Transform 父物体
--- @param prefabPath string 预制体路径  不传默认为：UICanvas
--- @param callback function 加载完成回调
function ResourceManager.LoadPrefabSync(parent, prefabPath, callback)
    local prefab = CS_ResourceManager.LoadPrefabSync(parent or UIRoot, prefabPath, callback)
    return prefab
end

--- LoadSprite 加载Sprite图片
--- @param atlasPath string 图集路径
--- @param spriteName string Sprite 图片名字
--- @return Sprite Sprite 图片
function ResourceManager.LoadSprite(atlasPath, spriteName)
    local sprite = CS_ResourceManager.LoadSprite(atlasPath, spriteName)
    return sprite
end

--- LoadTexture 加载Texture图片
--- @param textureName string Texture 图片名字
--- @return Texture Texture 图片
function ResourceManager.LoadTexture(textureName)
    local texture = CS_ResourceManager.LoadTexture(textureName)
    return texture
end

--- IsNull 判断一个obj是否为空（主要是用于检测Lua端已释放，但CS端还未释放的情况）
--- @param obj GameObject 物体
--- @return boolean 是否为空？ true ：是
function ResourceManager.IsNull(obj)
    local csNull = CS_ResourceManager.IsNull(obj)
    return (not obj) or csNull
end

--- Destroy 销毁物体
--- @param obj GameObject 要销毁的物体
function ResourceManager.Destroy(obj)
    if (not ResourceManager.IsNull(obj)) then
        Destroy(obj)
    end
    obj = nil
end

return ResourceManager