--- 全局变量在此定义
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/18 16:27
---

--- @field UIRoot Transform UI父节点
_G.UIRoot = GameObject.Find("UICanvas").transform

-- 销毁
_G.Destroy = UnityEngine.Object.Destroy

-- 是否是表
_G.IsTable = function(info)
    return type(info) == "table"
end

-- Log打印
_G.Log = function(info)
    local str = nil
    local isTable = IsTable(info)
    if (isTable) then
        str = string.format("Log:\n\n%s\n%s", dumpTableEx(info), debug.traceback())
    else
        str = string.format("Log:%s\n%s", dumpTableEx(info), debug.traceback())
    end
    Debug.Log(str)
end

-- Warning打印
_G.LogWarning = function(info)
    local str = nil
    local isTable = IsTable(info)
    if (isTable) then
        str = string.format("Warning:\n\n%s\n%s", dumpTableEx(info), debug.traceback())
    else
        str = string.format("Warning:%s\n%s", dumpTableEx(info), debug.traceback())
    end
    Debug.LogWarning(str)
end

-- Error打印
_G.LogError = function(info)
    local str = nil
    local isTable = IsTable(info)
    if (isTable) then
        str = string.format("Error:\n\n%s\n%s", dumpTableEx(info), debug.traceback())
    else
        str = string.format("Error:%s\n%s", dumpTableEx(info), debug.traceback())
    end
    Debug.LogError(str)
end