--- Lua端入口
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/10/9 15:20
---

package.cpath = package.cpath .. ';C:/Users/gan.qiang/.IntelliJIdea2018.3/config/plugins/intellij-emmylua/classes/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpListen('localhost', 9970)

Main = {}

--- 开始预加载模块
function InitRequire()
    require("PreLoad")
end

InitRequire()

--- Unity Awake
function OnAwake()
    LogError("按下 Q 键进入框架，且可开始断点调试")
end

--- Unity Start
function OnStart()
end

--- Unity Update
function OnUpdate()
    --LogError("OnUpdate")

    if (Input.GetKeyDown(KeyCode.Q)) then
        UIManager.OpenUI("MainWindow", args, callback)
    end
end

--- Unity FixedUpdate
function OnFixedUpdate()
    --LogError("OnFixedUpdate")
end

--- Unity LateUpdate
function OnLateUpdate()
    --LogError("OnLateUpdate")
end

--- Unity OnDestroy 在此处做游戏退出时的数据清理操作
function OnDestroy()
    --LogError("OnDestroy")

    UIManager.Clear()
    EventManager.ClearEvent()
end

return Main