--- 预加载模块
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/9 10:43
---

require("UnityEngineDefine")
require("HUtils")
require("Global")
require("LuaEx")
require("Class")
require("UIManager")
require("ResourceManager")
require("EventManager")
require("EventID")