--- Unity相关定义
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/10/9 16:11
---

UnityEngine = CS.UnityEngine

Debug = UnityEngine.Debug
Log = Debug.Log
LogWarning = Debug.LogWarning
LogError = Debug.LogError
GameObject = UnityEngine.GameObject
Transform = UnityEngine.Transform
Input = UnityEngine.Input
KeyCode = UnityEngine.KeyCode
Canvas = UnityEngine.Canvas
Application = UnityEngine.Application

Button = UnityEngine.UI.Button
Text = UnityEngine.UI.Text
Image = UnityEngine.UI.Image
RawImage = UnityEngine.UI.RawImage
Slider = UnityEngine.UI.Slider
Toggle = UnityEngine.UI.Toggle
ToggleGroup = UnityEngine.UI.ToggleGroup
ScrollRect = UnityEngine.UI.ScrollRect
LayoutRebuilder = UnityEngine.UI.LayoutRebuilder
GraphicRaycaster = UnityEngine.UI.GraphicRaycaster

CS_ResourceManager = CS.ResourceManager
UIElement = CS.UIElement