--- 整个框架的事件基类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/10 10:29
---

--- @class BaseEvent
local BaseEvent = Class.CreateClass("BaseEvent")

function BaseEvent:New()
    -- 存储的所有事件注册列表
    self.eventList = {}
end

--- AddListener 监听按钮事件
--- @param event Event 按钮onClick事件
--- @param callback function 按钮点击事件回调
function BaseEvent:AddListener(event, callback)
    if (not self.eventList[event]) then
        self.eventList[event]= {}
    end

    event:RemoveAllListeners()
    event:AddListener(function ()
        if (callback) then
            callback(self)
        end
    end)
end

--- ClearEvent 清理事件
function BaseEvent:ClearEvent()
    for event, _ in pairs(self.eventList) do
        event:RemoveAllListeners()
        event:Invoke()
    end
    self.eventList = {}
end

return BaseEvent