--- 所有物体的基类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/9 16:28
---

--- @class GameObject : BaseEvent
--- @field protected uiElements UIElement
local GameObject = Class.CreateClass("GameObject", "BaseEvent")

function GameObject:New()
end

--- SetObj 设置游戏物体
--- @param prefab GameObject 预制体
function GameObject:SetObj(prefab)
    self.gameObject = prefab
    self:BindUIElements()
end

--- BindUIElements 绑定UIElement（做到Lua端可以直接self.uiElements.xxx直接拿到Unity组件）
function GameObject:BindUIElements()
    local elements = self.uiElements
    if (HUtils.IsEmpty(elements)) then
        elements = {}
        self.uiElements = elements
        UIElement.TryBind(self.gameObject, elements)
    end
end

--- SetSprite 设置 Sprite 图片
--- @param image Image Image组件
--- @param atlasPath string 图集路径
--- @param spriteName string Sprite 图片名字
--- @param bNativeSize boolean 是否保持原图大小
function GameObject:SetSprite(image, atlasPath, spriteName, bNativeSize)
    if (ResourceManager.IsNull(image)) then
        LogError("传入的Image组件为空，请检查!!")
        return
    end

    image:SetSprite(atlasPath, spriteName, bNativeSize)
end

--- SetTexture 设置 Texture 图片
--- @param rawImage RawImage RawImage组件
--- @param textureName string Sprite 图片名字
--- @param bNativeSize boolean 是否保持原图大小
function GameObject:SetTexture(rawImage, textureName, bNativeSize)
    if (ResourceManager.IsNull(rawImage)) then
        LogError("传入的RawImage组件为空，请检查!!")
        return
    end

    rawImage:SetTexture(textureName, bNativeSize)
end

--- ClearGameObject 清理游戏物体
function GameObject:ClearGameObject()
    if (not ResourceManager.IsNull(self.gameObject)) then
        ResourceManager.Destroy(self.gameObject)
    end
    self.gameObject = nil
end

return GameObject