--- 工具类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/8 15:21
---

local HUtils = {}
_G.HUtils = HUtils

--- Clone 克隆表
function HUtils.Clone(object)
    local lookup_table = {}
    local function copyObj(object)
        if type(object) ~= "table" then
            return object
        elseif lookup_table[object] then
            return lookup_table[object]
        end

        local new_table = {}
        lookup_table[object] = new_table
        for key, value in pairs(object) do
            new_table[copyObj(key)] = copyObj(value)
        end
        return setmetatable(new_table, getmetatable(object))
    end
    return copyObj(object)
end

--- IsEmpty 判断表是否为空
function HUtils.IsEmpty(tab)
    if (tab == nil) or type(tab) ~= "table" then
        return true
    end

    local isNull = true
    for _, _ in pairs(tab) do
        isNull = false
        break
    end

    return isNull
end

return HUtils