--- Lua 扩展
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gan.qiang.
--- DateTime: 2022/11/8 17:26
---

local HUtils = require("HUtils")

--- 判断字符串是否为空
--- @param str string 字符串
--- @return boolean 字符串是否为空？ true ：是
--- @return string 传入的字符串
string.IsNullOrEmpty = function (str)
    return (not str) or (str == ""), str
end

--- 判断表内是否包涵某值
--- @param tab table 判断的表
--- @param value number 判断包涵的值
--- @return boolean 是否包涵该值？ true ：是
table.Comprise = function (tab, value)
    local isNotTable = type(tab) ~= "table"
    if (isNotTable) then
        return
    end

    local isEmpty = HUtils.IsEmpty(tab)
    if (isEmpty) then
        return
    end

    for _, val in pairs(tab) do
        if (value == val) then
            return true
        end
    end
end

--- 获得表的长度
--- @param tab table 表
--- @return number 表的长度
table.Count = function(tab)
    if (type(tab) ~= "table") then
        return 0
    end

    local count = 0
    for _, _ in pairs(tab) do
        count = count + 1
    end
    return count
end

--- 查找该值在列表中的位置
--- @param tab table
--- @param value any
--- @return number   (-1为不存在)
table.IndexOf = function(tab, value)
    if (type(tab) == "table") then
        for index = 1, table.Count(tab) do
            if (value == tab[index]) then
                return index
            end
        end
    end
    return -1
end